{
  parserClass="dev.lonami.uniffidl.parser.UdlParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Udl"
  psiImplClassSuffix="Impl"
  psiPackage="dev.lonami.uniffidl.psi"
  psiImplPackage="dev.lonami.uniffidl.psi.impl"
  psiImplUtilClass="dev.lonami.uniffidl.psi.impl.UdlPsiImplUtil"

  elementTypeHolderClass="dev.lonami.uniffidl.psi.UdlTypes"
  elementTypeClass="dev.lonami.uniffidl.psi.UdlElementType"
  tokenTypeClass="dev.lonami.uniffidl.psi.UdlTokenType"

  tokens=[
      OP_OPEN_PAREN="("
      OP_CLOSE_PAREN=")"
      OP_WILDCARD="*"
      OP_SEPARATOR=","
      OP_NEG="-"
      KW_NEGINF="-Infinity"
      OP_DOT="."
      OP_ELLIPSIS="..."
      OP_COLON=":"
      OP_SEMICOLON=";"
      OP_LESSTHAN="<"
      OP_EQUALS="="
      OP_GREATERTHAN=">"
      OP_NULLABLE="?"
      KW_POSINF="Infinity"
      KW_NAN="NaN"
      OP_OPEN_BRACKET="["
      OP_CLOSE_BRACKET="]"
      KW_ANY="any"
      KW_ASYNC="async"
      KW_ATTRIBUTE="attribute"
      KW_BIGINT="bigint"
      KW_BOOLEAN="boolean"
      KW_BYTE="byte"
      KW_CALLBACK="callback"
      KW_CONST="const"
      KW_CONSTRUCTOR="constructor"
      KW_DELETER="deleter"
      KW_DICTIONARY="dictionary"
      KW_DOUBLE="double"
      KW_ENUM="enum"
      KW_FALSE="false"
      KW_FLOAT="float"
      KW_GETTER="getter"
      KW_INCLUDES="includes"
      KW_INHERIT="inherit"
      KW_INTERFACE="interface"
      KW_ITERABLE="iterable"
      KW_LONG="long"
      KW_MAPLIKE="maplike"
      KW_MIXIN="mixin"
      KW_NAMESPACE="namespace"
      KW_NULL="null"
      KW_OBJECT="object"
      KW_OCTET="octet"
      KW_OPTIONAL="optional"
      KW_OR="or"
      KW_PARTIAL="partial"
      KW_READONLY="readonly"
      KW_RECORD="record"
      KW_REQUIRED="required"
      KW_SEQUENCE="sequence"
      KW_SETLIKE="setlike"
      KW_SETTER="setter"
      KW_SHORT="short"
      KW_STATIC="static"
      KW_STRING="string"
      KW_STRINGIFIER="stringifier"
      KW_SYMBOL="symbol"
      KW_TRUE="true"
      KW_TYPEDEF="typedef"
      KW_UNDEFINED="undefined"
      KW_UNRESTRICTED="unrestricted"
      KW_UNSIGNED="unsigned"
      OP_OPEN_BRACE="{"
      OP_PIPE="|"
      OP_CLOSE_BRACE="}"

      integer='regexp:-?([1-9][0-9]*|0[Xx][0-9A-Fa-f]+|0[0-7]*)'
      decimal='regexp:-?(([0-9]+\.[0-9]*|[0-9]*\.[0-9]+)([Ee][+-]?[0-9]+)?|[0-9]+[Ee][+-]?[0-9]+)'
      identifier='regexp:[_-]?[A-Za-z][0-9A-Z_a-z-]*'
      string='regexp:\"[^\"]*\"'
      whitespace='regexp:[\t\n\r ]+'
      comment='regexp://.*|/\*(.|\n)*?\*/'
      alt='regexp:[^\t\n\r 0-9A-Za-z]'
  ]
}

// Most of UDL comes from WebIDL's grammar at https://webidl.spec.whatwg.org/#idl-grammar

Definitions ::=
    (ExtendedAttributeList Definition Definitions)?

Definition ::=
    CallbackOrInterfaceOrMixin
    | Namespace
    | Partial
    | Dictionary
    | Enum
    | Typedef
    | IncludesStatement {
        mixin="dev.lonami.uniffidl.psi.impl.UdlNamedElementImpl"
        implements="dev.lonami.uniffidl.psi.UdlNamedElement"
        methods=[getNameIdentifier getName setName getPresentation]
    }

ArgumentNameKeyword ::=
    KW_ASYNC
    | KW_ATTRIBUTE
    | KW_CALLBACK
    | KW_CONST
    | KW_CONSTRUCTOR
    | KW_DELETER
    | KW_DICTIONARY
    | KW_ENUM
    | KW_GETTER
    | KW_INCLUDES
    | KW_INHERIT
    | KW_INTERFACE
    | KW_ITERABLE
    | KW_MAPLIKE
    | KW_MIXIN
    | KW_NAMESPACE
    | KW_PARTIAL
    | KW_READONLY
    | KW_REQUIRED
    | KW_SETLIKE
    | KW_SETTER
    | KW_STATIC
    | KW_STRINGIFIER
    | KW_TYPEDEF
    | KW_UNRESTRICTED

CallbackOrInterfaceOrMixin ::=
    KW_CALLBACK CallbackRestOrInterface
    | KW_INTERFACE InterfaceOrMixin

InterfaceOrMixin ::=
    InterfaceRest
    | MixinRest

InterfaceRest ::=
    identifier Inheritance OP_OPEN_BRACE InterfaceMembers OP_CLOSE_BRACE OP_SEMICOLON

Partial ::=
    KW_PARTIAL PartialDefinition

PartialDefinition ::=
    KW_INTERFACE PartialInterfaceOrPartialMixin
    | PartialDictionary
    | Namespace

PartialInterfaceOrPartialMixin ::=
    PartialInterfaceRest
    | MixinRest

PartialInterfaceRest ::=
    identifier OP_OPEN_BRACE PartialInterfaceMembers OP_CLOSE_BRACE OP_SEMICOLON

InterfaceMembers ::=
    (ExtendedAttributeList InterfaceMember InterfaceMembers)?

InterfaceMember ::=
    PartialInterfaceMember
    | Constructor

PartialInterfaceMembers ::=
    (ExtendedAttributeList PartialInterfaceMember PartialInterfaceMembers)?

PartialInterfaceMember ::=
    Const
    | Operation
    | Stringifier
    | StaticMember
    | Iterable
    | AsyncIterable
    | ReadOnlyMember
    | ReadWriteAttribute
    | ReadWriteMaplike
    | ReadWriteSetlike
    | InheritAttribute

Inheritance ::=
    (OP_COLON identifier)?

MixinRest ::=
    KW_MIXIN identifier OP_OPEN_BRACE MixinMembers OP_CLOSE_BRACE OP_SEMICOLON

MixinMembers ::=
    (ExtendedAttributeList MixinMember MixinMembers)?

MixinMember ::=
    Const
    | RegularOperation
    | Stringifier
    | OptionalReadOnly AttributeRest

IncludesStatement ::=
    identifier KW_INCLUDES identifier OP_SEMICOLON

CallbackRestOrInterface ::=
    CallbackRest
    | KW_INTERFACE identifier OP_OPEN_BRACE CallbackInterfaceMembers OP_CLOSE_BRACE OP_SEMICOLON

CallbackInterfaceMembers ::=
    (ExtendedAttributeList CallbackInterfaceMember CallbackInterfaceMembers)?

CallbackInterfaceMember ::=
    Const
    | RegularOperation

Const ::=
    KW_CONST ConstType identifier OP_EQUALS ConstValue OP_SEMICOLON

ConstValue ::=
    BooleanLiteral
    | FloatLiteral
    | integer

BooleanLiteral ::=
    KW_TRUE
    | KW_FALSE

FloatLiteral ::=
    decimal
    | KW_NEGINF
    | KW_POSINF
    | KW_NAN

ConstType ::=
    PrimitiveType
    | identifier

ReadOnlyMember ::=
    KW_READONLY ReadOnlyMemberRest

ReadOnlyMemberRest ::=
    AttributeRest
    | MaplikeRest
    | SetlikeRest

ReadWriteAttribute ::=
    AttributeRest

InheritAttribute ::=
    KW_INHERIT AttributeRest

AttributeRest ::=
    KW_ATTRIBUTE TypeWithExtendedAttributes AttributeName OP_SEMICOLON

AttributeName ::=
    AttributeNameKeyword
    | identifier

AttributeNameKeyword ::=
    KW_ASYNC
    | KW_REQUIRED

OptionalReadOnly ::=
    (KW_READONLY)?

DefaultValue ::=
    ConstValue
    | string
    | OP_OPEN_BRACKET OP_CLOSE_BRACKET
    | OP_OPEN_BRACE OP_CLOSE_BRACE
    | KW_NULL
    | KW_UNDEFINED

Operation ::=
    RegularOperation
    | SpecialOperation

RegularOperation ::=
    Type OperationRest {
        mixin="dev.lonami.uniffidl.psi.impl.UdlNamedElementImpl"
        implements="dev.lonami.uniffidl.psi.UdlNamedElement"
        methods=[getNameIdentifier getName setName getPresentation]
    }

SpecialOperation ::=
    Special RegularOperation

Special ::=
    KW_GETTER
    | KW_SETTER
    | KW_DELETER

OperationRest ::=
    OptionalOperationName OP_OPEN_PAREN ArgumentList OP_CLOSE_PAREN OP_SEMICOLON

OptionalOperationName ::=
    (OperationName)?

OperationName ::=
    OperationNameKeyword
    | identifier

OperationNameKeyword ::=
    KW_INCLUDES

ArgumentList ::=
    (Argument Arguments)?

Arguments ::=
    (OP_SEPARATOR Argument Arguments)?

Argument ::=
    ExtendedAttributeList ArgumentRest

ArgumentRest ::=
    KW_OPTIONAL TypeWithExtendedAttributes ArgumentName Default
    | Type Ellipsis ArgumentName

ArgumentName ::=
    ArgumentNameKeyword
    | identifier

Ellipsis ::=
    (OP_ELLIPSIS)?

Constructor ::=
    KW_CONSTRUCTOR OP_OPEN_PAREN ArgumentList OP_CLOSE_PAREN OP_SEMICOLON  {
        methods=[getPresentation]
    }

Stringifier ::=
    KW_STRINGIFIER StringifierRest

StringifierRest ::=
    OptionalReadOnly AttributeRest
    | OP_SEMICOLON

StaticMember ::=
    KW_STATIC StaticMemberRest

StaticMemberRest ::=
    OptionalReadOnly AttributeRest
    | RegularOperation

Iterable ::=
    KW_ITERABLE OP_LESSTHAN TypeWithExtendedAttributes OptionalType OP_GREATERTHAN OP_SEMICOLON

OptionalType ::=
    (OP_SEPARATOR TypeWithExtendedAttributes)?

AsyncIterable ::=
    KW_ASYNC KW_ITERABLE OP_LESSTHAN TypeWithExtendedAttributes OptionalType OP_GREATERTHAN OptionalArgumentList OP_SEMICOLON

OptionalArgumentList ::=
    (OP_OPEN_PAREN ArgumentList OP_CLOSE_PAREN)?

ReadWriteMaplike ::=
    MaplikeRest

MaplikeRest ::=
    KW_MAPLIKE OP_LESSTHAN TypeWithExtendedAttributes OP_SEPARATOR TypeWithExtendedAttributes OP_GREATERTHAN OP_SEMICOLON

ReadWriteSetlike ::=
    SetlikeRest

SetlikeRest ::=
    KW_SETLIKE OP_LESSTHAN TypeWithExtendedAttributes OP_GREATERTHAN OP_SEMICOLON

Namespace ::=
    KW_NAMESPACE identifier OP_OPEN_BRACE NamespaceMembers OP_CLOSE_BRACE OP_SEMICOLON

NamespaceMembers ::=
    (ExtendedAttributeList NamespaceMember NamespaceMembers)?

NamespaceMember ::=
    RegularOperation
    | KW_READONLY AttributeRest
    | Const

Dictionary ::=
    KW_DICTIONARY identifier Inheritance OP_OPEN_BRACE DictionaryMembers OP_CLOSE_BRACE OP_SEMICOLON

DictionaryMembers ::=
    (DictionaryMember DictionaryMembers)?

DictionaryMember ::=
    ExtendedAttributeList DictionaryMemberRest {
       mixin="dev.lonami.uniffidl.psi.impl.UdlNamedElementImpl"
       implements="dev.lonami.uniffidl.psi.UdlNamedElement"
       methods=[getNameIdentifier getName setName getPresentation]
   }

DictionaryMemberRest ::=
    KW_REQUIRED TypeWithExtendedAttributes identifier OP_SEMICOLON
    | Type identifier Default OP_SEMICOLON

PartialDictionary ::=
    KW_DICTIONARY identifier OP_OPEN_BRACE DictionaryMembers OP_CLOSE_BRACE OP_SEMICOLON

Default ::=
    (OP_EQUALS DefaultValue)?

Enum ::=
    KW_ENUM identifier OP_OPEN_BRACE EnumValueList OP_CLOSE_BRACE OP_SEMICOLON

EnumValueList ::=
    string EnumValueListComma

EnumValueListComma ::=
    (OP_SEPARATOR EnumValueListString)?

EnumValueListString ::=
    (string EnumValueListComma)?

CallbackRest ::=
    identifier OP_EQUALS Type OP_OPEN_PAREN ArgumentList OP_CLOSE_PAREN OP_SEMICOLON

Typedef ::=
    KW_TYPEDEF TypeWithExtendedAttributes identifier OP_SEMICOLON

Type ::=
    SingleType
    | UnionType Null

TypeWithExtendedAttributes ::=
    ExtendedAttributeList Type

SingleType ::=
    DistinguishableType
    | KW_ANY
    | PromiseType

UnionType ::=
    OP_OPEN_PAREN UnionMemberType KW_OR UnionMemberType UnionMemberTypes OP_CLOSE_PAREN

UnionMemberType ::=
    ExtendedAttributeList DistinguishableType
    | UnionType Null

UnionMemberTypes ::=
    (KW_OR UnionMemberType UnionMemberTypes)?

DistinguishableType ::=
    PrimitiveType Null
    | StringType Null
    | identifier Null
    | KW_SEQUENCE OP_LESSTHAN TypeWithExtendedAttributes OP_GREATERTHAN Null
    | KW_OBJECT Null
    | KW_SYMBOL Null
    | BufferRelatedType Null
    | "FrozenArray" OP_LESSTHAN TypeWithExtendedAttributes OP_GREATERTHAN Null
    | "ObservableArray" OP_LESSTHAN TypeWithExtendedAttributes OP_GREATERTHAN Null
    | RecordType Null
    | KW_UNDEFINED Null

PrimitiveType ::=
    UnsignedIntegerType
    | UnrestrictedFloatType
    | KW_BOOLEAN
    | KW_BYTE
    | KW_OCTET
    | KW_BIGINT

UnrestrictedFloatType ::=
    KW_UNRESTRICTED FloatType
    | FloatType

FloatType ::=
    KW_FLOAT
    | KW_DOUBLE

UnsignedIntegerType ::=
    KW_UNSIGNED IntegerType
    | IntegerType

IntegerType ::=
    KW_SHORT
    | KW_LONG OptionalLong

OptionalLong ::=
    (KW_LONG)?

StringType ::=
    KW_STRING
    | "ByteString"
    | "DOMString"
    | "USVString"

PromiseType ::=
    "Promise" OP_LESSTHAN Type OP_GREATERTHAN

RecordType ::=
    KW_RECORD OP_LESSTHAN StringType OP_SEPARATOR TypeWithExtendedAttributes OP_GREATERTHAN

Null ::=
    (OP_NULLABLE)?

BufferRelatedType ::=
    "ArrayBuffer"
    | "DataView"
    | "Int8Array"
    | "Int16Array"
    | "Int32Array"
    | "Uint8Array"
    | "Uint16Array"
    | "Uint32Array"
    | "Uint8ClampedArray"
    | "BigInt64Array"
    | "BigUint64Array"
    | "Float32Array"
    | "Float64Array"

ExtendedAttributeList ::=
    (OP_OPEN_BRACKET ExtendedAttribute ExtendedAttributes OP_CLOSE_BRACKET)?

ExtendedAttributes ::=
    (OP_SEPARATOR ExtendedAttribute ExtendedAttributes)?

ExtendedAttribute ::=
    OP_OPEN_PAREN ExtendedAttributeInner OP_CLOSE_PAREN ExtendedAttributeRest
    | OP_OPEN_BRACKET ExtendedAttributeInner OP_CLOSE_BRACKET ExtendedAttributeRest
    | OP_OPEN_BRACE ExtendedAttributeInner OP_CLOSE_BRACE ExtendedAttributeRest
    | Other ExtendedAttributeRest

ExtendedAttributeRest ::=
    (ExtendedAttribute)?

ExtendedAttributeInner ::=
    (OP_OPEN_PAREN ExtendedAttributeInner OP_CLOSE_PAREN ExtendedAttributeInner
    | OP_OPEN_BRACKET ExtendedAttributeInner OP_CLOSE_BRACKET ExtendedAttributeInner
    | OP_PIPE OP_OPEN_BRACE ExtendedAttributeInner OP_CLOSE_BRACE ExtendedAttributeInner
    | OP_PIPE OtherOrComma ExtendedAttributeInner)?

Other ::=
    integer
    | decimal
    | identifier
    | string
    | alt
    | OP_NEG
    | KW_NEGINF
    | OP_DOT
    | OP_ELLIPSIS
    | OP_COLON
    | OP_SEMICOLON
    | OP_LESSTHAN
    | OP_EQUALS
    | OP_GREATERTHAN
    | OP_NULLABLE
    | OP_WILDCARD
    | "ByteString"
    | "DOMString"
    | "FrozenArray"
    | KW_POSINF
    | KW_NAN
    | "ObservableArray"
    | "Promise"
    | "USVString"
    | KW_ANY
    | KW_BIGINT
    | KW_BOOLEAN
    | KW_BYTE
    | KW_DOUBLE
    | KW_FALSE
    | KW_FLOAT
    | KW_LONG
    | KW_NULL
    | KW_OBJECT
    | KW_OCTET
    | KW_OR
    | KW_OPTIONAL
    | KW_RECORD
    | KW_SEQUENCE
    | KW_SHORT
    | KW_SYMBOL
    | KW_TRUE
    | KW_UNSIGNED
    | KW_UNDEFINED
    | ArgumentNameKeyword
    | BufferRelatedType

OtherOrComma ::=
    Other
    | OP_SEPARATOR

IdentifierList ::=
    identifier Identifiers

Identifiers ::=
    (OP_SEPARATOR identifier Identifiers)?

ExtendedAttributeNoArgs ::=
    identifier

ExtendedAttributeArgList ::=
    identifier OP_OPEN_PAREN ArgumentList OP_CLOSE_PAREN

ExtendedAttributeIdent ::=
    identifier OP_EQUALS identifier

ExtendedAttributeWildcard ::=
    identifier OP_EQUALS OP_WILDCARD

ExtendedAttributeIdentList ::=
    identifier OP_EQUALS OP_OPEN_PAREN IdentifierList OP_CLOSE_PAREN

ExtendedAttributeNamedArgList ::=
    identifier OP_EQUALS identifier OP_OPEN_PAREN ArgumentList OP_CLOSE_PAREN
